djangoxoo/djangoxoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vesti.urls'))
]

djangoxoo/vesti/urls.py
from django.urls import path, re_path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('', views.index, name='vesti'),
    path('korisnici/',views.korisnici, name='korisnici'),
    path('komentari/',views.komentari,name='komentari'),
    path('int/<br>', views.broj, name='vesti_broj'),
    path('params/', views.query, name='vesti_query'),
    re_path(r'^regex/(?:godina-(?P<godina>[0-9]{4}))/(?:mesec-(?P<mesec>[0-9]{2}))', views.regex, name='vesti_regex'),#re_path = regex path
]

djangoxoo/vesti/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Cookies(models.Model):
    value = models.CharField(max_length=20)
    newsid = models.IntegerField(db_column='newsId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'cookies'


class Komentari(models.Model):
    author = models.CharField(max_length=20)
    content = models.CharField(max_length=100)
    news = models.IntegerField()
    likes = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'komentari'


class Korisnici(models.Model):
    email = models.CharField(unique=True, max_length=20)
    password = models.CharField(max_length=100)
    tip = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'korisnici'


class Lajkovi(models.Model):
    value = models.CharField(max_length=20)
    commentid = models.IntegerField(db_column='commentId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'lajkovi'


class Vesti(models.Model):
    author = models.CharField(max_length=20)
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=200)
    count = models.IntegerField()
    category = models.CharField(max_length=20)
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'vesti'

djangoxoo/vesti/forms.py
from django.forms import ModelForm
from .models import Komentari, Korisnici, Vesti

djangoxoo/vesti/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Vesti, Korisnici, Komentari, Cookies

def index(request, x=0):
    tmp = Vesti.objects.all()
    if 'q' in request.GET:
        q = request.GET['q']
        tmp = Vesti.objects.filter(content__icontains=q) | Vesti.objects.filter(title__icontains=q)

    elif 'date' in request.GET:
        #request.GET.get('date')
        order = request.GET['date']
        if order == 'ASC':
            tmp = Vesti.objects.all().order_by('date')
        elif order == 'DSC':
            tmp = Vesti.objects.all().order_by('-date')

    elif 'sort' in request.GET:
        #request.GET.get('sort')
        order = request.GET['sort']
        if order == 'ASC':
            tmp = Vesti.objects.all().order_by('count')
        elif order == 'DSC':
            tmp = Vesti.objects.all().order_by('-count')

    elif 'kategorija' in request.GET:
        request.GET.get('kategorija')
        kategorija = request.GET['kategorija']
        tmp = Vesti.objects.filter(category=kategorija)

    for vest in tmp:
        x += vest.count

    f = []
    for vest in Vesti.objects.all():
        if vest.category in f:
            continue
        else:
            f.append(vest.category)

    g = {}
    for vest in Vesti.objects.all():
        if vest.id in g:
            continue
        else:
            g[vest.id] = 0

    for vest in Vesti.objects.all():
        for komentar in Komentari.objects.all():
            if komentar.news == vest.id:
                g[vest.id] += 1

    return render(request, 'vesti.html', {'vesti':tmp, 'x':x, 'kategorije':f, 'komentari':g})

def korisnici(request):
    tmp = Korisnici.objects.all()

    if 'name' in request.GET:
        name = request.GET['name']
        tmp = Korisnici.objects.filter(name__icontains=name)

    elif 'surname' in request.GET:
        surname = request.GET['surname']
        tmp = Korisnici.objects.filter(surname__icontains=surname)

    elif 'type' in request.GET:
        type = request.GET['type']
        tmp = Korisnici.objects.filter(tip__icontains=type)

    admins = 0
    creators = 0
    for korisnik in Korisnici.objects.all():
        if korisnik.tip == 'ADMIN':
            admins += 1
        if korisnik.tip == 'CONTENT_CREATOR':
            creators += 1

    o = []

    for guest in Cookies.objects.all():
        if guest.value in o:
            continue
        else:
            o.append(guest.value)

    guests = len(o)

    return render(request, 'korisnici.html', {'korisnici':tmp, 'admins':admins, 'creators':creators, 'guests':guests})

def komentari(request):
    tmp = Komentari.objects.all()
    maxi = 0
    maxKomentar = None
    for komentar in tmp:
        if komentar.likes > maxi:
            maxi = komentar.likes
            maxKomentar = Komentari.objects.get(id=komentar.id)

    lajkovi = 0
    for komentar in tmp:
        lajkovi += komentar.likes

    d = {}
    for komentar in tmp:
        if komentar.news in d:
            d[komentar.news] += 1
        else:
            d[komentar.news] = 1

    max_value = max(d.values())
    max_key = None
    for k,v in d.items():
        if v == max_value:
            max_key = k
    print(max_key)

    n = Vesti.objects.get(id=max_key)

    return render(request, 'komentari.html', {'komentari':tmp,'lajkovi':lajkovi,'maxKomentar':maxKomentar,
                                              'brKomentara':max_value, 'vest':n})

def broj(request,br):
    return HttpResponse('Broj: ' + str(br))

def query(request):
    return HttpResponse('Params: ' + request.GET.get('ime', ''))

def regex(request, godina, mesec):
    return HttpResponse('Godina: ' + godina + 'Mesec: ' + mesec)

djangoxoo/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'my_app:vesti' %}">
        News review
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:korisnici' %}">Users review</a>
        </li>
    </ul>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:komentari' %}">Comments review</a>
        </li>
    </ul>

</nav>

djangoxoo/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyNews</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'header.html' %}

    <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <h1>TEST MASTER TEMPLATE</h1>
            {% endblock content %}
    </div>

</body>
</html>

djangoxoo/vesti/templates/komentari.html
{%  extends 'master.html' %}

{%  block content %}
    <div class="list-group">
        <h1>Number of Comments: {{komentari.count}}</h1>
        <h1>Ukupan broj lajkova: {{lajkovi}}</h1>
        <br/>
        <h1>Most popular comment:</h1>
        <div class="border">
            <h1>Author: {{maxKomentar.author}}</h1>
            <h2>Comment: {{maxKomentar.content}}</h2>
            <h3>Likes: {{maxKomentar.likes}}</h3>
            </div>
        <br/>
        <h1>Vest sa najvise komentara:({{brKomentara}}) </h1>
        <div class="border">
            <h1>{{ vest.title }}</h1>
            <p>{{vest.content}}</p>
            <h2>Views: {{vest.count}}</h2>
            <h3>Category: {{vest.category}}</h3>
            <h4>Datum: {{vest.date}}</h4>
        </div>
    </div>
{% endblock %}

djangoxoo/vesti/templates/korisnici.html
{%  extends 'master.html' %}

{%  block content %}
    <div class="list-group">
        <h1>Number of Users: {{korisnici.count}}</h1>
        <h1>Admins: {{admins}}</h1>
        <h1>Content Creators: {{creators}}</h1>
        <h1>Guests: {{guests}}</h1>
        <br/>

    <form action="{% url 'my_app:korisnici' %}">
        <div class="input-group mb-3">
            <input name = "name" type="text" class="form-control" placeholder="Search Name" aria-label="Search Name" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary">Search</button>
            </div>
        </div>
    </form>
        <br/>
        <br/>

    <form action="{% url 'my_app:korisnici' %}">
        <div class="input-group mb-3">
            <input name = "surname" type="text" class="form-control" placeholder="Search Surname" aria-label="Search Surname" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary">Search</button>
            </div>
        </div>
    </form>
        <br/>
        <br/>

    <form action="{% url 'my_app:korisnici' %}">
        <div class="input-group mb-3">
            <input name = "type" type="text" class="form-control" placeholder="Search type" aria-label="Search type" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary">Search</button>
            </div>
        </div>
    </form>
        <br/>
        {% for korisnik in korisnici %}
        <div class="border">
            <h1>email: {{korisnik.email}}</h1>
            <h2>name: {{korisnik.name}}</h2>
            <h3>surname: {{korisnik.surname}}</h3>
            <h4>role: {{korisnik.tip}}</h4>
        </div>
        {% endfor %}
    </div>
{% endblock %}

djangoxoo/vesti/templates/vesti.html
{%  extends 'master.html' %}

{%  block content %}
    <h1>Ukupno vesti: {{vesti.count}}</h1>
    <br/>
    <h2>Broj pregleda: {{x}}</h2>
    <br/>
    <form action="{% url 'my_app:vesti' %}">
        <div class="input-group mb-3">
            <input name = "q" type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary">Search</button>
            </div>
        </div>
    </form>
    <br/>
    <div class="btn-group" role="group" aria-label="FilterButtons">
    <form action="{% url 'my_app:vesti' %}" method="get">
        <button class="btn btn-outline-secondary" name="sort" value="ASC" type="submit">OrderViewsASC</button>
        <button class="btn btn-outline-secondary" name="sort" value="DSC" type="submit">OrderViewsDSC</button>
    </form>
    <form action="{% url 'my_app:vesti' %}" method="get">
        <button class="btn btn-outline-secondary" name="date" value="ASC" type="submit">OrderDateASC</button>
        <button class="btn btn-outline-secondary" name="date" value="DSC" type="submit">OrderDateDSC</button>
    </form>
    </div>
    <br/>
    <div class="btn-group" role="group" aria-label="CategoryButtons">
        {% for kategorija in kategorije %}
        <form action="{% url 'my_app:vesti' %}" method="get">
            <button class="btn btn-outline-secondary" name="kategorija" value="{{kategorija}}" type="submit">
                {{kategorija}}</button>
        </form>
        {% endfor %}
    </div>

    <div class="list-group">
        {% for vest in vesti %}
        <div class="border">
            <h1>{{ vest.title }}</h1>
            <p>{{vest.content}}</p>
            <h2>Views: {{vest.count}}</h2>
            <h3>Category: {{vest.category}}</h3>
            <h4>Date Created: {{vest.date}}</h4>
        </div>
        {% endfor %}
    </div>
    <br/>

{% endblock %}